### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by sinamics**
Updates:
```json
"next": "^14.1.4",
"prisma": "^5.11.0",
"tailwindcss": "^3.4.3",
"typescript": "^5.4.3"
```

### CODE REVIEW

**Comment by sinamics** [comment]
@tinola would these versions work for you?

**Comment by tinola** [comment]
1.
`"next": "^14.1.4",`

This is OK, but I still have to apply dirty hack to use swc-wasm edition because of this:
```
 ✓ Checking validity of types
   Creating an optimized production build ...
   Downloading swc package @next/swc-freebsd-x64...
 ⨯ Failed to download swc package from https://registry.npmjs.org/@next/swc-freebsd-x64/-/swc-freebsd-x64-14.1.4.tgz
Error: request failed with status 404
```

Dirty patch for `node_modules/next/dist/build/swc/index.js`:

```
--- index.js.orig       2024-02-08 09:37:43.117670000 +0100
+++ index.js    2024-02-07 13:28:27.482293000 +0100
@@ -244,7 +244,8 @@ async function loadBindings(useWasmBinary = false) {
         const disableWasmFallback = process.env.NEXT_DISABLE_SWC_WASM;
         const unsupportedPlatform = triples.some((triple)=>!!(triple == null ? void 0 : triple.raw) && knownDefaultWasmFallbackTriples.includes(triple.raw));
         const isWebContainer = process.versions.webcontainer;
-        const shouldLoadWasmFallbackFirst = !disableWasmFallback && unsupportedPlatform && useWasmBinary || isWebContainer;
+        // const shouldLoadWasmFallbackFirst = !disableWasmFallback && unsupportedPlatform && useWasmBinary || isWebContainer;
+        const shouldLoadWasmFallbackFirst = true
         if (!unsupportedPlatform && useWasmBinary) {
             _log.warn(`experimental.useWasmBinary is not an option for supported platform ${PlatformName}/${ArchName} and will be ignored.`);
         }
```
After this ztnet is building just fine.

`
Downloading swc package @next/swc-wasm-nodejs...
`

2.
`"prisma": "^5.11.0",`

This is strange - with this line prisma client was generated as version 5.6.0.
I have to run inside ztnet folder these two commands:

```
npm i --save-dev prisma@latest
npm i @prisma/client@latest

```
After this prisma was generated as v5.11.0.

3.
```
"tailwindcss": "^3.4.3",
"typescript": "^5.4.3"
```

Those two lines are just OK.

**Comment by tinola** [comment]
BTW, so it seems, next-swc just did f**k up with builds packages for FreeBSD and some Linux archs...

https://github.com/vercel/next.js/issues/59997?notification_referrer_id=NT_kwDOADA4PbI4OTA0MDQwMzQwOjMxNjAxMjU#issuecomment-2028240633

and here some details:

https://github.com/vercel/next.js/blob/4efe14238b5ab11935e73aa09631ef5ec8045b13/packages/next/src/build/swc/index.ts#L52

I can't believe, what a mo..ns :(

Now, the goal is how to prepare `ztnet` to use `wasm` edition of `next-swc` to use with deprecated OS'es...
Is there any possibility to do it in package.json file with some conditions?
I mean:
```
if my_os_is_deprecated {
  use next-swc-wasm
} else { 
  do not use next-swc-wasm
}
```

**Comment by sinamics** [comment]
> Now, the goal is how to prepare ztnet to use wasm edition of next-swc to use with deprecated OS'es...
Is there any possibility to do it in package.json file with some conditions?

its not possible to set conditions directly in package-json to my knowledge, but we could do these checks in the installer script. 
if you know the exact os versions that needs the wasm edition i can add it in.

**Comment by tinola** [comment]
Understood.

So analysing [https://github.com/vercel/next.js/blob/4efe14238b5ab11935e73aa09631ef5ec8045b13/packages/next/src/build/swc/index.ts#L122](url) there're some triples which falling back to use wasm bindings.
FreeBSD OS triple is listed (however does not load wasm during build process, wrrr), and Linux OS'es installed on armv7 architecture devices, for example Raspberry Pi 4B is worth to test if wasm edition is loading during build... Unfortunately I haven't got RPi to do that :(

**Comment by tinola** [comment]
@sinamics, I think you can merge this PR into main anyway :)

**Pull request merged**
