### PR TITLE
mkworld for building private root

### LINKED ISSUE #76: [Feature Request]: Building planet server
### 🚀 Feature Summary

Support planet building

### 📝 Detailed Description

using mkworld to build planet file, so i can be a private planet root.

https://github.com/kmahyyg/ztncui-aio

### 🎯 Use Case

_No response_

### 💡 Willing to Contribute

Yes, I could help with testing

### PR DESCRIPTION
**Pull request by sinamics**
- [x] Add mkworld go source
- [x] Build multiarch binaries
- [x] Add frontend interaction to build planet file with user defined config ( endpoint and domain )
- [x] Add backup logic to easily revert the original files.
- [x] Add option to download new planet file
- [x] Add option to restore from previous backups
- [x] Translations 

Im on thin ice here, as im not familiar with custom roots, but it seems like the mkworld generating new planet file based on the given configuration and then its just a matter of copy this file to zerotier-one dir with right permissions. 
It will also create couple of signed files which i belive is the private keys that needs to be kept privatly.

resolves #76

### CODE REVIEW

**Comment by sinamics** [comment]
I believe I'm making good progress. The system now generates a new 'planet' based on the provided configuration while also creating backups of the previous configurations. I'm considering adding a feature to allow users to download or restore previous configurations.

For distribution, users have the option to either download the new 'planet' file or share it via email. Additionally, for added convenience, the external IP is automatically prepopulated.
image

**Comment by sinamics** [comment]
seems to be working fine. 
When custom planet has been created and zerotier container has been restarted, the zt root servers are not listed anymore. 
Also, when adding the custom planet to one of my peer im able to connect.

However, its probably a good pratice to block [zerotier roots](https://zerotier.atlassian.net/wiki/spaces/SD/pages/7241732/Root+Server+IP+Addresses) in iptables to be absolute sure its a private world.

image

**Comment by v808comd** [comment]
ff20230821000048

How can these three input boxes be updated after inputting characters? I tried clicking elsewhere with the mouse and couldn't update it. If I click Enter, it will be submitted directly.

**Comment by sinamics** [comment]
@v808comd 
There will be an improved version in next release. Most likely tonight. 
image

**Comment by sinamics** [comment]
I will also change the ::9993 => ::/9993

**Pull request merged**
